# -*- coding: utf-8 -*-
"""Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7LKw6s_wSqk3DIYw6b7oTHGiEJRpbxk
"""

!pip install pandas textblob matplotlib seaborn
!python -m textblob.download_corpora

import pandas as pd
import re
from textblob import TextBlob

df = pd.read_csv("/content/Tweets.csv")

df = df[['text', 'airline_sentiment']]

df.dropna(subset=['text'], inplace=True)

def clean_text(text):
    text = str(text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"[^A-Za-z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['clean_text'] = df['text'].apply(clean_text)

def get_polarity(text):
    return TextBlob(text).sentiment.polarity

df['polarity'] = df['clean_text'].apply(get_polarity)

final_df = df[['clean_text', 'airline_sentiment']]
final_df.columns = ['tweet', 'sentiment']

final_df.drop_duplicates(subset='tweet', inplace=True)
final_df = final_df.sample(n=5000, random_state=42)

final_df.to_csv("final_twitter_sentiment.csv", index=False)

print("✅ Final CSV created with shape:", final_df.shape)